# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    root = {
      device = "/dev/disk/by-uuid/030a9f92-07cf-4762-9d31-ece2323785e8";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/mapper/encrypted--vg-btrfs";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "ssd" "noatime" "space_cache" "commit=120" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/encrypted--vg-btrfs";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "ssd" "noatime" "space_cache" "commit=120" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88A1-C147";
      fsType = "vfat";
    };

  swapDevices =
    [ {
        # device = "/dev/disk/by-uuid/337ea93b-59f2-48b9-98cd-396d496c129f";
        device = "/dev/mapper/encrypted--vg-swap";
      }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
